server:
  port: 9097
spring:
  application:
    name: auditor
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres_database
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: test-kafka-cluster
    bootstrap-servers: localhost:9095
test:
  topic: audit-topic
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
