server:
  port: 9097
spring:
  cloud:
    kubernetes:
      enabled: false
      reload:
        enabled: false
  application:
    name: auditor
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    password: postgres
    url: jdbc:postgresql://postgres:5432/postgres_database
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: test-kafka-cluster
      bootstrap-servers: kafka-service:9092
test:
  topic: test_topic
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
