server:
  port: 9095

spring:
  cloud:
    discovery:
      enabled: 'false'
  application:
    name: auth-service

app:
  config:
    keycloak:
      auth-url: http://keycloak:8080/auth/realms/micro-dev/protocol/openid-connect/token
      logout-url: http://keycloak:8080/auth/realms/micro-dev/protocol/openid-connect/logout
      realm: micro-dev
      client-id: micro-dev-client
      client-secret: Zg2QXXWliYwiCQTPPDDYImHYkRbNdlEf

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
