server:
  port: 9095

spring:
  cloud:
    kubernetes:
    loadbalancer:
      mode: SERVICE
      discovery:
        discovery-server-url: https://spring-cloud-kubernetes-discoveryserver:8761
      enabled: true
      reload:
        enabled: true
  application:
    name: auth-service

app:
  config:
    keycloak:
      auth-url: http://keycloak:8080/auth/realms/micro-dev/protocol/openid-connect/token
      logout-url: http://keycloak:8080/auth/realms/micro-dev/protocol/openid-connect/logout
      realm: micro-dev
      client-id: micro-dev-client
      client-secret: Zg2QXXWliYwiCQTPPDDYImHYkRbNdlEf

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
