spring:
  cloud:
    kubernetes:
      discovery:
        discovery-server-url: https://spring-cloud-kubernetes-discoveryserver:8761
      enabled: true
server:
  port: "8082"
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
