spring:
  cloud:
    kubernetes:
      loadbalancer:
        mode: service
      enabled: true
server:
  port: "8082"
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
